package mx.uam.skynet.app.presentacion;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import mx.uam.skynet.app.persistencia.ConnectDB;

/**
 *
 * @author Familia
 */
public class ModificarCita extends JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form Modificar_cita
     */
    public ModificarCita(String folio) {
        initComponents(folio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(final String folio) {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Fecha_nueva_cita = new javax.swing.JTextField();
        Folio_cita = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arabic Typesetting", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modificar Cita");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 660, 30);

        jLabel3.setFont(new java.awt.Font("Arabic Typesetting", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Folio de Cita:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 80, 160, 30);
        
        jLabel2.setFont(new java.awt.Font("Arabic Typesetting", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fecha Próxima Cita:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 140, 160, 30);
       
        Fecha_nueva_cita.setForeground(new java.awt.Color(204, 204, 204));
        Fecha_nueva_cita.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Fecha_nueva_cita.setText("AAAA-MM-DD HH:MM");
       
        jPanel1.add(Fecha_nueva_cita);
        Fecha_nueva_cita.setBounds(250, 140, 370, 30);
        Fecha_nueva_cita.addMouseListener(new MouseListener() {
        	
        	@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
        		Fecha_nueva_cita.setText("");
        		Fecha_nueva_cita.setForeground(Color.BLACK);
        		
			}
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			
		});

        Folio_cita.setForeground(new java.awt.Color(204, 204, 204));
        Folio_cita.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Folio_cita.setText("Folio de cita a cambiar");
        Folio_cita.addMouseListener(new MouseListener() {
			
			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				Folio_cita.setText("");
				Folio_cita.setForeground(Color.BLACK);
			}

			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}

			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
		});
        
       
        jPanel1.add(Folio_cita);
        Folio_cita.setBounds(250, 80, 370, 30);

        jButton1.setText("Cancelar Cita");
        jPanel1.add(jButton1);
        jButton1.setBounds(410, 230, 190, 50);
        
//        ADD ACTIONLISTENER "CANCELAR CITA"

        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
				ConnectDB cn = new ConnectDB();
				int Confirm;
				Confirm=JOptionPane.showConfirmDialog(null, "Esta seguro de Cancelar la cita");
				if(JOptionPane.OK_OPTION == Confirm){
					cn.cancelButton(folio, Integer.parseInt(Folio_cita.getText()),Fecha_nueva_cita.getText());
					JOptionPane.showMessageDialog(null, "Se ha actualizado la pr\u00f3xima cita al d\u00eda: "+Fecha_nueva_cita.getText());
					try {
						HistorialClinico newwindows;
						newwindows = new HistorialClinico(folio);
						newwindows.dispose();
						newwindows.setVisible(true);
						newwindows.setTitle("Historial Cl\u00ednico");
						Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
						int height = screen.height;
						int width = screen.width;
						newwindows.setLocation(50, 50);
						newwindows.setSize(width-100, height-100);
						newwindows.setResizable(false);
					} catch (Exception e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
				}
				else{
					JOptionPane.showMessageDialog(null,"Se han cancelado la posposici\u00f3n exitosamente");					
				}
	}});
    
    

        
        jButton2.setText("Volver al Historial");
        jPanel1.add(jButton2);
        jButton2.setBounds(230, 330, 190, 50);
        
//        ADD ACTIONLISTENER "VOLVER AL HISTORIAL"
        
        jButton2.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				
				dispose();
			}
		});

        jButton3.setText("ACTUALIZAR");
        jPanel1.add(jButton3);
        jButton3.setBounds(80, 230, 190, 50);
        
//        ADD ACTIONLISTENER "ACTUALIZAR"
        
        jButton3.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				ConnectDB cn = new ConnectDB();
				
					int Confirm;
					Confirm=JOptionPane.showConfirmDialog(null, "Esta seguro de querer posponer la cita a "+Fecha_nueva_cita.getText());
					if(JOptionPane.OK_OPTION == Confirm){
						cn.postponeButton(folio, Integer.parseInt(Folio_cita.getText()),Fecha_nueva_cita.getText());
						JOptionPane.showMessageDialog(null, "Se ha actualizado la pr\u00f3xima cita al d\u00eda: "+Fecha_nueva_cita.getText());
						try {
							HistorialClinico newwindows;
							newwindows = new HistorialClinico(folio);
							newwindows.dispose();
							newwindows.setVisible(true);
							newwindows.setTitle("Historial Cl\u00ednico");
							Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
							int height = screen.height;
							int width = screen.width;
							newwindows.setLocation(50, 50);
							newwindows.setSize(width-100, height-100);
							newwindows.setResizable(false);
						} catch (Exception e1) {
							// TODO Auto-generated catch block
							e1.printStackTrace();
						}
					}
					else{
						JOptionPane.showMessageDialog(null,"Se han cancelado la posposici\u00f3n exitosamente");					
					}
		}});
        
        

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    
    /**
     * @param args the command line arguments
     */
//  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField Fecha_nueva_cita;
    private javax.swing.JTextField Folio_cita;
    // End of variables declaration//GEN-END:variables
}

