package mx.uam.skynet.app.presentacion;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.PreparedStatement;
import java.sql.SQLException;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import mx.uam.skynet.app.negocio.ControlModificarCita;
import mx.uam.skynet.app.persistencia.ConnectDB;
import mx.uam.skynet.app.persistencia.Querys;

/**
 *
 * @author Jesus Cerna Medina
 */
public class VentanaModificarCita extends JFrame {

	private static final long serialVersionUID = 1L;
	private ControlModificarCita ctrl;
	
    public VentanaModificarCita(ControlModificarCita ctrl) {
    	this.ctrl = ctrl;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fh_nueva_cita = new javax.swing.JTextField();
        num_cita = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        setTitle("Modificar cita");
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modificar Cita");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 660, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Numero de Cita:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 80, 160, 30);
        
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fecha Próxima Cita:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 140, 160, 30);
       
        fh_nueva_cita.setForeground(new java.awt.Color(204, 204, 204));
        fh_nueva_cita.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fh_nueva_cita.setText("AAAA-MM-DD HH:MM");
        
        jPanel1.add(fh_nueva_cita);
        fh_nueva_cita.setBounds(250, 140, 370, 30);
        fh_nueva_cita.addMouseListener(new MouseListener() {
        	@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
        		fh_nueva_cita.setText("");
        		fh_nueva_cita.setForeground(Color.BLACK);
			}

			@Override
			public void mouseEntered(MouseEvent e) {
			}

			@Override
			public void mouseExited(MouseEvent e) {	
			}

			@Override
			public void mousePressed(MouseEvent e) {
			}

			@Override
			public void mouseReleased(MouseEvent e) {
			}	
		});

        num_cita.setForeground(new java.awt.Color(204, 204, 204));
        num_cita.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        num_cita.setText("Folio de cita a cambiar");
        num_cita.addMouseListener(new MouseListener() {
			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				num_cita.setText("");
				num_cita.setForeground(Color.BLACK);
			}

			@Override
			public void mouseEntered(MouseEvent arg0) {
			}

			@Override
			public void mouseExited(MouseEvent arg0) {
			}

			@Override
			public void mousePressed(MouseEvent arg0) {
			}

			@Override
			public void mouseReleased(MouseEvent arg0) {
			}
		});
        
       
        jPanel1.add(num_cita);
        num_cita.setBounds(250, 80, 370, 30);

        jButton1.setText("Cancelar Cita");
        jPanel1.add(jButton1);
        jButton1.setBounds(410, 230, 190, 50);
        
//        ADD ACTIONLISTENER "CANCELAR CITA"

        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		int confirm = JOptionPane.showConfirmDialog(null, "Esta seguro de Cancelar la cita");
        		if (JOptionPane.OK_OPTION == confirm) {
        			boolean delete = ctrl.cancelarCita(num_cita.getText());
        			if (delete) {
        				JOptionPane.showMessageDialog(null, "Se ha cancelado la pr\u00f3xima");
					} else {
						JOptionPane.showMessageDialog(null, "Ocurrio un problema al borrar la fila. Verifica la informacion."+fh_nueva_cita);
					}
				} else {
					JOptionPane.showMessageDialog(null,"Se han cancelado la posposici\u00f3n exitosamente");
				}
        	}
        });
    
//      ADD ACTIONLISTENER "ACTUALIZAR"
        
        jButton3.addActionListener(new ActionListener() {
        	@Override
			public void actionPerformed(ActionEvent e) {
        		int confirm = JOptionPane.showConfirmDialog(null, "Esta seguro de querer posponer la cita a "+fh_nueva_cita.getText());
        		if (JOptionPane.OK_OPTION == confirm) {
        			boolean delete = ctrl.modificarCita(num_cita.getText(), fh_nueva_cita.getText());
        			if (delete) {
        				JOptionPane.showMessageDialog(null, "Se ha actualizado la pr\u00f3xima cita al d\u00eda: "+fh_nueva_cita.getText());
					} else {
						JOptionPane.showMessageDialog(null, "Ocurrio un problema al actualizar la fila. Verifica la informacion."+fh_nueva_cita);
					}
				} else {
					JOptionPane.showMessageDialog(null,"Se han cancelado la posposici\u00f3n exitosamente");
				}
        	}
        });

        
        jButton2.setText("Volver al Historial");
        jPanel1.add(jButton2);
        jButton2.setBounds(230, 330, 190, 50);
        
//        ADD ACTIONLISTENER "VOLVER AL HISTORIAL"
        
        jButton2.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				dispose();
			}
		});

        jButton3.setText("ACTUALIZAR");
        jPanel1.add(jButton3);
        jButton3.setBounds(80, 230, 190, 50);
        
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		try {
			ControlModificarCita ctrl = new ControlModificarCita(2);
			VentanaModificarCita dialog = new VentanaModificarCita(ctrl);
			dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
			dialog.setVisible(true);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
//  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField fh_nueva_cita;
    private javax.swing.JTextField num_cita;
    // End of variables declaration//GEN-END:variables
}

